### PR TITLE
Workaround for panic when Consul Service is stopped

### PR DESCRIPTION
**Pull request by lenny-intel**
Addresses issue #3

### CODE REVIEW

**Comment by tsconn23** [comment]
Hold label added pending one week triage period for PR submitted against upstream repo. https://github.com/mitchellh/consulstructure/pull/2

**Comment by tsconn23** [comment]
@lenny-intel Should we pull this in?

**Comment by lenny-intel** [comment]
@tsconn23 , we had discussed pulling consulstructure into the consul implementation if no action on my PR that fixes the issue, rather than have this work around.   No action for 2 weeks on my PR... :-( So I recommend we just integrate my fork that fixes the issue into go-mod-registry.

**Comment by tsconn23** [comment]
@lenny-intel Alright, so we'll close this and you'll create a new PR?

**Comment by lenny-intel** [comment]
@tsconn23 , Yes. Closing this PR as it is a work around. Will incorporate code from fork (mitchellh/consulstructure#2) that has fix.

**Pull request closed without merging**
